//go:build integration

package fingerprint_test

import (
	"context"
	"testing"

	"purser/internal/adapters/fingerprint"
	"purser/internal/domain"
)

// TestBookFingerprinter_Integration_EPUB exercises EPUB metadata extraction
// using "The Yellow Wallpaper" by Charlotte Perkins Gilman from Project Gutenberg (public domain).
// The test downloads the EPUB on first run and caches it in testdata/.
//
// Run with:
//
//	go test -tags integration -run TestBookFingerprinter_Integration_EPUB ./internal/adapters/fingerprint/
func TestBookFingerprinter_Integration_EPUB(t *testing.T) {
	const (
		fixtureURL    = "https://www.gutenberg.org/cache/epub/1952/pg1952.epub"
		fixtureName   = "yellow_wallpaper.epub"
		wantTitle     = "The Yellow Wallpaper"
		wantCreator   = "Charlotte Perkins Gilman"
	)

	path := downloadFixture(t, fixtureName, fixtureURL)

	fp := fingerprint.NewBookFingerprinter()
	result, err := fp.Fingerprint(context.Background(), domain.ScannedFile{
		Path:        path,
		ContentType: domain.ContentTypeBook,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil Fingerprint")
	}
	if result.EmbeddedTags["title"] != wantTitle {
		t.Errorf("title = %q, want %q", result.EmbeddedTags["title"], wantTitle)
	}
	if result.EmbeddedTags["creator"] != wantCreator {
		t.Errorf("creator = %q, want %q", result.EmbeddedTags["creator"], wantCreator)
	}
}

// TestBookFingerprinter_Integration_PDF exercises PDF Info dict extraction via pdfcpu
// using a minimal PDF generated by buildTestPDF. The fixture is cached in testdata/sample.pdf.
//
// Run with:
//
//	go test -tags integration -run TestBookFingerprinter_Integration_PDF ./internal/adapters/fingerprint/
func TestBookFingerprinter_Integration_PDF(t *testing.T) {
	const (
		wantTitle   = "Integration Test PDF"
		wantCreator = "Test Author"
	)

	path := buildTestPDF(t, wantTitle, wantCreator)

	fp := fingerprint.NewBookFingerprinter()
	result, err := fp.Fingerprint(context.Background(), domain.ScannedFile{
		Path:        path,
		ContentType: domain.ContentTypeBook,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result == nil {
		t.Fatal("expected non-nil Fingerprint")
	}
	if result.EmbeddedTags["title"] != wantTitle {
		t.Errorf("title = %q, want %q", result.EmbeddedTags["title"], wantTitle)
	}
	if result.EmbeddedTags["creator"] != wantCreator {
		t.Errorf("creator = %q, want %q", result.EmbeddedTags["creator"], wantCreator)
	}
}
